name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: Build the Docker image
      run: docker build ./src -t octavius

    - name: Log into registry
      run: echo "${{ secrets.nsc_key }}" | docker login ninjasoftware.azurecr.io -u ninjasoftware --password-stdin
    
    - name: Push the docker image
      run: |
        docker tag octavius ninjasoftware.azurecr.io/octavius
        docker push ninjasoftware.azurecr.io/octavius
